/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.IGenericController;
import Controladores.MenusController;
import Modelos.Menus;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Marlon Ramirez
 */
public class mainPage extends javax.swing.JFrame {

    private IGenericController registerController = new MenusController();
    
    /**
     * Creates new form mainPage
     */
    public mainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        submit_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        veg_rbtn = new javax.swing.JRadioButton();
        ham_rbtn = new javax.swing.JRadioButton();
        pizza_rbtn = new javax.swing.JRadioButton();
        salchi_rbtn = new javax.swing.JRadioButton();
        empanada_rbtn = new javax.swing.JRadioButton();
        papa_rbtn = new javax.swing.JRadioButton();
        maltcomb_rbtn = new javax.swing.JRadioButton();
        parcomb_rbtn = new javax.swing.JRadioButton();
        famcomb_rbtn = new javax.swing.JRadioButton();
        solocomb_rbtn = new javax.swing.JRadioButton();
        dulcecomb_rbtn = new javax.swing.JRadioButton();
        tosti_rbtn = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        name_text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dir_text = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        celular_text = new javax.swing.JTextField();
        detail_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        salsa_checkbox = new javax.swing.JCheckBox();
        papas_checkbox = new javax.swing.JCheckBox();
        gaseosa_checkbox = new javax.swing.JCheckBox();
        picante_checkbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("RESTAURANTE POO");
        jLabel1.setToolTipText("");

        submit_btn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        submit_btn.setText("Hacer orden");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 0));
        jLabel2.setText("Sus Datos:");
        jLabel2.setToolTipText("");

        veg_rbtn.setText("Vegetariano");
        veg_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veg_rbtnActionPerformed(evt);
            }
        });

        ham_rbtn.setText("Hamburguesa");
        ham_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ham_rbtnActionPerformed(evt);
            }
        });

        pizza_rbtn.setText("Pizza");
        pizza_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizza_rbtnActionPerformed(evt);
            }
        });

        salchi_rbtn.setText("Salchipapa");
        salchi_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salchi_rbtnActionPerformed(evt);
            }
        });

        empanada_rbtn.setText("Empanadas");
        empanada_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empanada_rbtnActionPerformed(evt);
            }
        });

        papa_rbtn.setText("PapaRellena");
        papa_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papa_rbtnActionPerformed(evt);
            }
        });

        maltcomb_rbtn.setText("Combo Malteada");
        maltcomb_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maltcomb_rbtnActionPerformed(evt);
            }
        });

        parcomb_rbtn.setText("Combo Pareja");
        parcomb_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parcomb_rbtnActionPerformed(evt);
            }
        });

        famcomb_rbtn.setText("Combo Pollo Familiar");
        famcomb_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                famcomb_rbtnActionPerformed(evt);
            }
        });

        solocomb_rbtn.setText("Combo Solo");
        solocomb_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solocomb_rbtnActionPerformed(evt);
            }
        });

        dulcecomb_rbtn.setText("Combo Dulceros");
        dulcecomb_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dulcecomb_rbtnActionPerformed(evt);
            }
        });

        tosti_rbtn.setText("TostiArepas");
        tosti_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tosti_rbtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre:");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 0));
        jLabel4.setText("Seleccione el Menú que desea:");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Dirección: ");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("No. Celular:");
        jLabel6.setToolTipText("");

        detail_btn.setText("Ver detalle");
        detail_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detail_btnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 0));
        jLabel7.setText("Extras:");
        jLabel7.setToolTipText("");

        salsa_checkbox.setText("Salsas Extras");

        papas_checkbox.setText("Porción de papas");

        gaseosa_checkbox.setText("Gaseosa");

        picante_checkbox.setText("Picante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submit_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(detail_btn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(veg_rbtn)
                                            .addComponent(empanada_rbtn)
                                            .addComponent(papa_rbtn)
                                            .addComponent(salchi_rbtn)
                                            .addComponent(pizza_rbtn)
                                            .addComponent(ham_rbtn))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tosti_rbtn, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(solocomb_rbtn, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(famcomb_rbtn, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(parcomb_rbtn, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(maltcomb_rbtn, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dulcecomb_rbtn, javax.swing.GroupLayout.Alignment.LEADING))))
                                .addGap(59, 59, 59))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(dir_text, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(gaseosa_checkbox)
                                                        .addComponent(salsa_checkbox)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(celular_text, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(picante_checkbox)
                                                    .addComponent(papas_checkbox)))))
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(veg_rbtn)
                    .addComponent(maltcomb_rbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ham_rbtn)
                    .addComponent(parcomb_rbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pizza_rbtn)
                    .addComponent(famcomb_rbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salchi_rbtn)
                    .addComponent(solocomb_rbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(papa_rbtn)
                    .addComponent(dulcecomb_rbtn))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empanada_rbtn)
                    .addComponent(tosti_rbtn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(detail_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salsa_checkbox)
                    .addComponent(papas_checkbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(picante_checkbox)
                    .addComponent(gaseosa_checkbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dir_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celular_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        //Campos de texto
        String Direccion = dir_text.getText();
        String Nombre = name_text.getText();
        String Celular = celular_text.getText();

        //JCheckBox y JRadioButton
        //Tipo de menu
        boolean Vegano = veg_rbtn.isSelected();
        boolean Hamburguesa = ham_rbtn.isSelected();
        boolean Pizza = pizza_rbtn.isSelected();
        boolean Salchipapa = salchi_rbtn.isSelected();
        boolean PapaRellena = papa_rbtn.isSelected();
        boolean Empanada = empanada_rbtn.isSelected();
        boolean ComboMalteada = maltcomb_rbtn.isSelected();
        boolean ComboPareja = parcomb_rbtn.isSelected();
        boolean ComboPolloFamiliar = famcomb_rbtn.isSelected();
        boolean ComboSolo = solocomb_rbtn.isSelected();
        boolean ComboDulcero = dulcecomb_rbtn.isSelected();
        boolean TostiArepas = tosti_rbtn.isSelected();

        //Extras
        boolean SalsasExtras = salsa_checkbox.isSelected();
        boolean PapasExtras = papas_checkbox.isSelected();
        boolean Gaseosa = gaseosa_checkbox.isSelected();
        boolean Picante = picante_checkbox.isSelected();

        //Validaciones
        if ((Direccion.isEmpty() || Nombre.isEmpty() || Celular.isEmpty())
                || (
                    !Vegano && 
                    !Hamburguesa && 
                    !Pizza && 
                    !Salchipapa && 
                    !PapaRellena && 
                    !Empanada && 
                    !ComboMalteada && 
                    !ComboPareja && 
                    !ComboPolloFamiliar && 
                    !ComboSolo && 
                    !ComboDulcero && 
                    !TostiArepas)
            ) 
        {
            System.out.println("Por favor defina los parametros correctamente");
            return;
        }

        String TipoMenuSelected = "";

        if (Vegano) {
            TipoMenuSelected = "Vegano";
        }
        if (Hamburguesa) {
            TipoMenuSelected = "Hamburguesa";
        }
        if (Pizza) {
            TipoMenuSelected = "Pizza";
        }
        if (Salchipapa) {
            TipoMenuSelected = "Salchipapa";
        }
        if (PapaRellena) {
            TipoMenuSelected = "PapaRellena";
        }
        if (Empanada) {
            TipoMenuSelected = "Empanada";
        }
        if (ComboMalteada) {
            TipoMenuSelected = "ComboMalteada";
        }
        if (ComboPareja) {
            TipoMenuSelected = "ComboPareja";
        }
        if (ComboPolloFamiliar) {
            TipoMenuSelected = "ComboPolloFamiliar";
        }
        if (ComboSolo) {
            TipoMenuSelected = "ComboSolo";
        }
        if (ComboDulcero) {
            TipoMenuSelected = "ComboDulcero";
        }
        if (TostiArepas) {
            TipoMenuSelected = "TostiArepas";
        }
        

        List<String> Extras = new ArrayList<>();

        if (SalsasExtras) {
            Extras.add("Salsas Extra");
        };
        if (PapasExtras) {
            Extras.add("Papas Extra");
        };
        if (Gaseosa) {
            Extras.add("Gaseosa");
        };
        if (Picante) {
            Extras.add("Picante");
        };

        Menus menuObj = new Menus(
                TipoMenuSelected,
                Nombre,
                Direccion,
                Celular,
                Extras
        );

        //Llamada al registro
        boolean resp = registerController.crearRegistro(menuObj);

        if (resp) {
            System.out.println("Pedido registrado correctamente");
        } else {
            System.out.println("El registro salió mal");
            return;
        }
    }//GEN-LAST:event_submit_btnActionPerformed

    private void veg_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veg_rbtnActionPerformed
        ham_rbtn.setSelected(false);
        pizza_rbtn.setSelected(false);
        salchi_rbtn.setSelected(false);
        papa_rbtn.setSelected(false);
        empanada_rbtn.setSelected(false);
        maltcomb_rbtn.setSelected(false);
        parcomb_rbtn.setSelected(false);
        famcomb_rbtn.setSelected(false);
        solocomb_rbtn.setSelected(false);
        dulcecomb_rbtn.setSelected(false);
        tosti_rbtn.setSelected(false);
    }//GEN-LAST:event_veg_rbtnActionPerformed

    private void detail_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detail_btnActionPerformed
        //Tipo de menu
        boolean Vegano = veg_rbtn.isSelected();
        boolean Hamburguesa = ham_rbtn.isSelected();
        boolean Pizza = pizza_rbtn.isSelected();
        boolean Salchipapa = salchi_rbtn.isSelected();
        boolean PapaRellena = papa_rbtn.isSelected();
        boolean Empanada = empanada_rbtn.isSelected();
        boolean ComboMalteada = maltcomb_rbtn.isSelected();
        boolean ComboPareja = parcomb_rbtn.isSelected();
        boolean ComboPolloFamiliar = famcomb_rbtn.isSelected();
        boolean ComboSolo = solocomb_rbtn.isSelected();
        boolean ComboDulcero = dulcecomb_rbtn.isSelected();
        boolean TostiArepas = tosti_rbtn.isSelected();
        
        
        int TipoMenuSelected = 0;

        if (Vegano) {
            TipoMenuSelected = 1;
        }
        if (Hamburguesa) {
            TipoMenuSelected = 2;
        }
        if (Pizza) {
            TipoMenuSelected = 3;
        }
        if (Salchipapa) {
            TipoMenuSelected = 4;
        }
        if (PapaRellena) {
            TipoMenuSelected = 5;
        }
        if (Empanada) {
            TipoMenuSelected = 6;
        }
        if (ComboMalteada) {
            TipoMenuSelected = 7;
        }
        if (ComboPareja) {
            TipoMenuSelected = 8;
        }
        if (ComboPolloFamiliar) {
            TipoMenuSelected = 9;
        }
        if (ComboSolo) {
            TipoMenuSelected = 10;
        }
        if (ComboDulcero) {
            TipoMenuSelected = 11;
        }
        if (TostiArepas) {
            TipoMenuSelected = 12;
        }
        
        //Obtener el contenido del Menu
        String menuDesc = registerController.obtenerMenu(TipoMenuSelected);
        
        System.out.println(menuDesc);
    }//GEN-LAST:event_detail_btnActionPerformed

    private void ham_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ham_rbtnActionPerformed
        veg_rbtn.setSelected(false);
        pizza_rbtn.setSelected(false);
        salchi_rbtn.setSelected(false);
        papa_rbtn.setSelected(false);
        empanada_rbtn.setSelected(false);
        maltcomb_rbtn.setSelected(false);
        parcomb_rbtn.setSelected(false);
        famcomb_rbtn.setSelected(false);
        solocomb_rbtn.setSelected(false);
        dulcecomb_rbtn.setSelected(false);
        tosti_rbtn.setSelected(false);
    }//GEN-LAST:event_ham_rbtnActionPerformed

    private void pizza_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizza_rbtnActionPerformed
        veg_rbtn.setSelected(false);
        ham_rbtn.setSelected(false);
        salchi_rbtn.setSelected(false);
        papa_rbtn.setSelected(false);
        empanada_rbtn.setSelected(false);
        maltcomb_rbtn.setSelected(false);
        parcomb_rbtn.setSelected(false);
        famcomb_rbtn.setSelected(false);
        solocomb_rbtn.setSelected(false);
        dulcecomb_rbtn.setSelected(false);
        tosti_rbtn.setSelected(false);
    }//GEN-LAST:event_pizza_rbtnActionPerformed

    private void salchi_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salchi_rbtnActionPerformed
        veg_rbtn.setSelected(false);
        ham_rbtn.setSelected(false);
        pizza_rbtn.setSelected(false);
        papa_rbtn.setSelected(false);
        empanada_rbtn.setSelected(false);
        maltcomb_rbtn.setSelected(false);
        parcomb_rbtn.setSelected(false);
        famcomb_rbtn.setSelected(false);
        solocomb_rbtn.setSelected(false);
        dulcecomb_rbtn.setSelected(false);
        tosti_rbtn.setSelected(false);
    }//GEN-LAST:event_salchi_rbtnActionPerformed

    private void papa_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papa_rbtnActionPerformed
        veg_rbtn.setSelected(false);
        ham_rbtn.setSelected(false);
        pizza_rbtn.setSelected(false);
        salchi_rbtn.setSelected(false);
        empanada_rbtn.setSelected(false);
        maltcomb_rbtn.setSelected(false);
        parcomb_rbtn.setSelected(false);
        famcomb_rbtn.setSelected(false);
        solocomb_rbtn.setSelected(false);
        dulcecomb_rbtn.setSelected(false);
        tosti_rbtn.setSelected(false);
    }//GEN-LAST:event_papa_rbtnActionPerformed

    private void empanada_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empanada_rbtnActionPerformed
        veg_rbtn.setSelected(false);
        ham_rbtn.setSelected(false);
        pizza_rbtn.setSelected(false);
        salchi_rbtn.setSelected(false);
        papa_rbtn.setSelected(false);
        maltcomb_rbtn.setSelected(false);
        parcomb_rbtn.setSelected(false);
        famcomb_rbtn.setSelected(false);
        solocomb_rbtn.setSelected(false);
        dulcecomb_rbtn.setSelected(false);
        tosti_rbtn.setSelected(false);
    }//GEN-LAST:event_empanada_rbtnActionPerformed

    private void maltcomb_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maltcomb_rbtnActionPerformed
        veg_rbtn.setSelected(false);
        ham_rbtn.setSelected(false);
        pizza_rbtn.setSelected(false);
        salchi_rbtn.setSelected(false);
        papa_rbtn.setSelected(false);
        empanada_rbtn.setSelected(false);
        parcomb_rbtn.setSelected(false);
        famcomb_rbtn.setSelected(false);
        solocomb_rbtn.setSelected(false);
        dulcecomb_rbtn.setSelected(false);
        tosti_rbtn.setSelected(false);
    }//GEN-LAST:event_maltcomb_rbtnActionPerformed

    private void parcomb_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parcomb_rbtnActionPerformed
        veg_rbtn.setSelected(false);
        ham_rbtn.setSelected(false);
        pizza_rbtn.setSelected(false);
        salchi_rbtn.setSelected(false);
        papa_rbtn.setSelected(false);
        empanada_rbtn.setSelected(false);
        maltcomb_rbtn.setSelected(false);
        famcomb_rbtn.setSelected(false);
        solocomb_rbtn.setSelected(false);
        dulcecomb_rbtn.setSelected(false);
        tosti_rbtn.setSelected(false);
    }//GEN-LAST:event_parcomb_rbtnActionPerformed

    private void famcomb_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_famcomb_rbtnActionPerformed
        veg_rbtn.setSelected(false);
        ham_rbtn.setSelected(false);
        pizza_rbtn.setSelected(false);
        salchi_rbtn.setSelected(false);
        papa_rbtn.setSelected(false);
        empanada_rbtn.setSelected(false);
        maltcomb_rbtn.setSelected(false);
        parcomb_rbtn.setSelected(false);
        solocomb_rbtn.setSelected(false);
        dulcecomb_rbtn.setSelected(false);
        tosti_rbtn.setSelected(false);
    }//GEN-LAST:event_famcomb_rbtnActionPerformed

    private void solocomb_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solocomb_rbtnActionPerformed
        veg_rbtn.setSelected(false);
        ham_rbtn.setSelected(false);
        pizza_rbtn.setSelected(false);
        salchi_rbtn.setSelected(false);
        papa_rbtn.setSelected(false);
        empanada_rbtn.setSelected(false);
        maltcomb_rbtn.setSelected(false);
        parcomb_rbtn.setSelected(false);
        famcomb_rbtn.setSelected(false);
        dulcecomb_rbtn.setSelected(false);
        tosti_rbtn.setSelected(false);
    }//GEN-LAST:event_solocomb_rbtnActionPerformed

    private void dulcecomb_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dulcecomb_rbtnActionPerformed
        veg_rbtn.setSelected(false);
        ham_rbtn.setSelected(false);
        pizza_rbtn.setSelected(false);
        salchi_rbtn.setSelected(false);
        papa_rbtn.setSelected(false);
        empanada_rbtn.setSelected(false);
        maltcomb_rbtn.setSelected(false);
        parcomb_rbtn.setSelected(false);
        famcomb_rbtn.setSelected(false);
        solocomb_rbtn.setSelected(false);
        tosti_rbtn.setSelected(false);
    }//GEN-LAST:event_dulcecomb_rbtnActionPerformed

    private void tosti_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tosti_rbtnActionPerformed
        veg_rbtn.setSelected(false);
        ham_rbtn.setSelected(false);
        pizza_rbtn.setSelected(false);
        salchi_rbtn.setSelected(false);
        papa_rbtn.setSelected(false);
        empanada_rbtn.setSelected(false);
        maltcomb_rbtn.setSelected(false);
        parcomb_rbtn.setSelected(false);
        famcomb_rbtn.setSelected(false);
        solocomb_rbtn.setSelected(false);
        dulcecomb_rbtn.setSelected(false);
    }//GEN-LAST:event_tosti_rbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField celular_text;
    private javax.swing.JButton detail_btn;
    private javax.swing.JTextField dir_text;
    private javax.swing.JRadioButton dulcecomb_rbtn;
    private javax.swing.JRadioButton empanada_rbtn;
    private javax.swing.JRadioButton famcomb_rbtn;
    private javax.swing.JCheckBox gaseosa_checkbox;
    private javax.swing.JRadioButton ham_rbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton maltcomb_rbtn;
    private javax.swing.JTextField name_text;
    private javax.swing.JRadioButton papa_rbtn;
    private javax.swing.JCheckBox papas_checkbox;
    private javax.swing.JRadioButton parcomb_rbtn;
    private javax.swing.JCheckBox picante_checkbox;
    private javax.swing.JRadioButton pizza_rbtn;
    private javax.swing.JRadioButton salchi_rbtn;
    private javax.swing.JCheckBox salsa_checkbox;
    private javax.swing.JRadioButton solocomb_rbtn;
    private javax.swing.JButton submit_btn;
    private javax.swing.JRadioButton tosti_rbtn;
    private javax.swing.JRadioButton veg_rbtn;
    // End of variables declaration//GEN-END:variables
}
